### ISSUE TITLE
SC 3.3

### ISSUE THREAD

**Issue by katabolerTeufel** [Skhmt/mfd#1]
Are you planning to upgrade the mfd for star citizen 3.3?
Best regards

**Comment by Skhmt** [comment]
That's the plan!

Any specific suggestions?

**Comment by katabolerTeufel** [comment]
That's good to hear, then I haven't to develop my own :|. What I prefer is a grid that i can customize for my own preferences. And maybe a vertical slider for acceleration.

**Comment by katabolerTeufel** [comment]
That's good to hear, then I haven't to develop my own :|. What I prefer is a grid that i can customize for my own preferences. And maybe a vertical slider for acceleration.

**Comment by Skhmt** [comment]
It'll all depend on what keybinds allow in 3.3, whenever 3.3 comes out.

**Comment by Sonny-Crockett** [comment]
Does 3.3 come with expanded key bind support?

**Comment by hardwire666** [comment]
Currently using on the 3.3 PTU and works just fine as is.

**Comment by Skhmt** [comment]
I won't have a gaming computer for a couple weeks, but I'll revisit this when I do and see if there's anything I can make better or add. Specific suggestions welcome of course.

**Comment by hardwire666** [comment]
Honestly none I can think of. I've Been using MFD for a month at this point And I even prefer it over LEA Extended as it performs faster.

On second thought some comment blocks in the included displays CSS would be helpful.

**Comment by Skhmt** [comment]
I'm definitely considering splitting all the displays (besides the example) into a separate github project so I can update those without incrementing the main program's version number.

I'll try to go through stuff and comment everything as much as possible.

**Comment by hardwire666** [comment]
Separate githubs for the different displays is a good idea.

**Comment by katabolerTeufel** [comment]
Thats a great Idea @hardwire

**Comment by Skhmt** [comment]
Done and done.

Star Citizen: https://github.com/Skhmt/mfd-starcitizen

Diablo 3: https://github.com/Skhmt/mfd-diablo3
