### ISSUE TITLE
Windows focus specification

### ISSUE THREAD

**Issue by arolust** [Skhmt/mfd#2]
Any chance of a future feature for detecting the window/processor in focus and changing layout for specific matches?

**Comment by Skhmt** [comment]
That would be amazing, but at least for now, it would be a TON of work. This answer on StackOverflow seems to more-or-less cover it, but I'll do some brainstorming:

https://stackoverflow.com/a/18275492

**Comment by Skhmt** [comment]
Eh, figured something out, released as 1.5.0 :)
